### PR TITLE
Use `extract-procedure`.

### LINKED ISSUE #18: Can't disassemble
```
$ racket
Welcome to Racket v8.5.0.7 [cs].
> (require disassemble my-lib)
> (disassemble a-proc-of-my-lib)
inspector-object: invalid message 'code to object type 'record [,bt for context]
> ,bt
inspector-object: invalid message 'code to object type 'record
  context...:
   /usr/local/google/home/lorseau/.local/share/racket/snapshot/pkgs/disassemble/disassemble/main.rkt:142:5: body of top-level
   /usr/local/google/home/lorseau/.local/share/racket/snapshot/pkgs/disassemble/disassemble/main.rkt:193:0: disassemble
   /usr/share/racket-8.5.0.7/pkgs/xrepl-lib/xrepl/xrepl.rkt:1573:0
   /usr/share/racket-8.5.0.7/collects/racket/repl.rkt:11:26
> 
```
The same happens whether I remove zos or recompile beforehand.

The basic example of the docs does work though.

### PR DESCRIPTION
**Pull request by samth**
This should fix #18 but doesn't for reasons that I don't yet understand.

### CODE REVIEW

**Comment by samth** [comment]
Note that this code works, so I'm confused:

```
#lang racket/base

(define (f #:x [x #f]) (+ x 1))

(require ffi/unsafe/vm)

(define extract-procedure (vm-eval '(lambda (x) (extract-procedure x #f))))

(eq? f (extract-procedure f))

f
(extract-procedure f)
(require disassemble)

(disassemble (extract-procedure f))
```

**Comment by samth** [comment]
@metaxal If you can see what I've done wrong here, I'm sure it's dumb.

**Comment by Metaxal** [comment]
I have no clue about what's going on here, sorry. I checked for impersonators (though I don't understand that stuff much) in case that would defeat the `eq?` but they all return `#f` so I guess they are indeed `eq?`. And then I'm at a loss, since `(disassemble f)` still raises an exception.

**Comment by Metaxal** [comment]
Could it be about transparency, code inspectors and such, that behave differently in the two cases?

**Comment by samth** [comment]
@Metaxal can you confirm that the patch in this PR doesn't fix the big for you, but that the code snippet does work?

**Pull request merged**
